# Basic
title: Allen Kashiwa Blog
subtitle: 羁旅红尘不曾醉，笑歌年少且长行。
welcome_message: 唯佳人与游戏不可辜负
description: 专注游戏开发与设计
creator: <a href="http://baizihan.me">@baizihan</a>

url: "http://www.baizihan.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
# markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    # comment for project button
    # - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    - {title: 微博, description: 我的微博, url: 'http://weibo.com/allenkashiwa'}
    - {title: 知乎, description: 我的知乎, url: 'https://www.zhihu.com/people/baizihan'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    duoshuo: kashiwa
    
# Social
social:
    weibo: allenkashiwa
    github: AllenKashiwa
    # twitter: onevcat
    # gplus: 107108267983477358170
    mail: 358804906@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
